### ISSUE TITLE
Montagem Tela - Tele-Entrega

### ISSUE THREAD

**Issue by antoniogabrielti** [andrepenha/analistaccnapenha#24]
montar uma tela inicial de alguma funcionalidade associada ao caso de uso Tele-Entrega

**Comment by andrepenha** [comment]
Inserido no repositório principal um PROJETO BETA

**Comment by andrepenha** [comment]
Acertado com o grupo. Cada um faz sua tela.

**Comment by roavellarm** [comment]
Tela pronta.
