### ISSUE TITLE
Menu vendas - Alteração Condomínio, Bloco, AP e Símbolo Moeda R$

### ISSUE THREAD

**Issue by andrepenha** [andrepenha/analistaccnapenha#32]

**Comment by roavellarm** [comment]
1) Criar um campo para cada um dos seguintes:
- Condominio
- Bloco
- Ap

2) Adicionar simbolo de moeda "R$" nos títulos das ultimas duas colunas.

3) Retirar "por produto" no título da última coluna da tabela ""Valor total por produto".

4) Rever a cor dos botoes
